// Regenerates public/locations.js — built-in climate presets for Iraqi cities.
// Source: NASA POWER climatology (long-term monthly means), the same API the app
// queries live for any map location. Run: node scripts/fetch-climate.mjs
import { writeFile } from 'node:fs/promises';

const CITIES = [
  ['Baghdad', 33.315, 44.366], ['Basra', 30.508, 47.783], ['Mosul', 36.340, 43.130],
  ['Erbil', 36.191, 44.009], ['Sulaymaniyah', 35.557, 45.435], ['Kirkuk', 35.468, 44.392],
  ['Duhok', 36.867, 42.988], ['Zakho', 37.144, 42.682], ['Tikrit', 34.607, 43.678],
  ['Baqubah', 33.746, 44.643], ['Ramadi', 33.426, 43.299], ['Rutba', 33.038, 40.284],
  ['Karbala', 32.616, 44.025], ['Najaf', 32.026, 44.346], ['Hillah', 32.468, 44.420],
  ['Kut', 32.506, 45.818], ['Diwaniyah', 31.990, 44.925], ['Samawah', 31.317, 45.280],
  ['Nasiriyah', 31.052, 46.257], ['Amarah', 31.836, 47.145],
];
const MONTHS = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];

const out = [];
for (const [name, lat, lon] of CITIES) {
  const url = `https://power.larc.nasa.gov/api/temporal/climatology/point?parameters=ALLSKY_SFC_SW_DWN,T2M&community=RE&longitude=${lon}&latitude=${lat}&format=JSON`;
  const p = (await (await fetch(url)).json()).properties.parameter;
  out.push({ name, lat, lon,
    ghi: MONTHS.map(m => +p.ALLSKY_SFC_SW_DWN[m].toFixed(2)),
    tamb: MONTHS.map(m => +p.T2M[m].toFixed(1)) });
  console.log(name, p.ALLSKY_SFC_SW_DWN.ANN);
}

const body = `// AUTO-GENERATED by scripts/fetch-climate.mjs on ${new Date().toISOString().slice(0, 10)} — do not edit by hand.
// Long-term monthly means from NASA POWER (power.larc.nasa.gov), RE community climatology:
//   ghi  = all-sky surface shortwave downward irradiance, kWh/m²/day
//   tamb = air temperature at 2 m, °C
export const CITIES = ${JSON.stringify(out, null, 0).replace(/\},\{/g, '},\n  {').replace('[{', '[\n  {').replace('}]', '},\n]')};
`;
await writeFile(new URL('../public/locations.js', import.meta.url), body);
console.log(`Wrote ${out.length} cities`);
